image:
  file: .gitpod.Dockerfile
tasks:
  - init: pip install -r requirements.txt
    command: python app.py
ports:
  - port: 5000
    onOpen: open-preview
vscode:
  extensions:
    - littlefoxteam.vscode-python-test-adapter@0.3.16:tZ/6xOSSdKUaq6JCUVkD+A==