image:
  file: .gitpod.Dockerfile
tasks:
  - init: pip install pipenv 
    command: pipenv install --dev
    command: pipenv run python app.py
ports:
  - port: 5000
    onOpen: open-preview
vscode:
  extensions:
    - littlefoxteam.vscode-python-test-adapter@0.3.16:tZ/6xOSSdKUaq6JCUVkD+A==