codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "50...100"
  status:
    patch:
      default:
        # basic
        target: 50
        threshold: 70%
        base: auto
    project:
      default:
        # basic
        target: 50
        threshold: 10%
        base: auto

ignore:
  - "app.py"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
