codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "50...100"

coverage:
  status:
    patch:
      default:
        # basic
        target: auto
        threshold: 0%
        base: auto

  coverage:
    status:
      project:
        default:
          # basic
          target: auto
          threshold: 0%
          base: auto
          flags:
            - unit
          paths:
            - "src"

ignore:
  - "app.py"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
